/*
 * Commspace source data API
 * API for Commspace source data management
 *
 * OpenAPI spec version: 1.0.2
 * Contact: api@commspace.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * AgreementComplianceStatus
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-08T15:04:17.157Z[GMT]")
public class AgreementComplianceStatus {
  @JsonProperty("compliant")
  private Boolean compliant = null;

  @JsonProperty("reason")
  private String reason = null;

  public AgreementComplianceStatus compliant(Boolean compliant) {
    this.compliant = compliant;
    return this;
  }

   /**
   * flag indicating compliance status of product
   * @return compliant
  **/
  @Schema(example = "true", required = true, description = "flag indicating compliance status of product")
  public Boolean isCompliant() {
    return compliant;
  }

  public void setCompliant(Boolean compliant) {
    this.compliant = compliant;
  }

  public AgreementComplianceStatus reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * textual description of reason for compliance status. required if compliant is false.
   * @return reason
  **/
  @Schema(description = "textual description of reason for compliance status. required if compliant is false.")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementComplianceStatus agreementComplianceStatus = (AgreementComplianceStatus) o;
    return Objects.equals(this.compliant, agreementComplianceStatus.compliant) &&
        Objects.equals(this.reason, agreementComplianceStatus.reason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(compliant, reason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementComplianceStatus {\n");
    
    sb.append("    compliant: ").append(toIndentedString(compliant)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
