/*
 * Commspace source data API
 * API for Commspace source data management
 *
 * OpenAPI spec version: 1.0.4
 * Contact: api@commspace.co.za
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.AgreementComplianceStatus;
import io.swagger.client.model.IntermediarySplit;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;
/**
 * Holds details of an agreement for an individual product. Includes compliance status, effective date of the agreement and the intermediaries who participate in the agreement
 */
@Schema(description = "Holds details of an agreement for an individual product. Includes compliance status, effective date of the agreement and the intermediaries who participate in the agreement")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-31T07:42:49.936Z[GMT]")
public class Agreement {
  @SerializedName("compliance_status")
  private AgreementComplianceStatus complianceStatus = null;

  @SerializedName("intermediary_splits")
  private List<IntermediarySplit> intermediarySplits = new ArrayList<IntermediarySplit>();

  @SerializedName("effective_date")
  private LocalDate effectiveDate = null;

  @SerializedName("reference_number")
  private String referenceNumber = null;

  public Agreement complianceStatus(AgreementComplianceStatus complianceStatus) {
    this.complianceStatus = complianceStatus;
    return this;
  }

   /**
   * Get complianceStatus
   * @return complianceStatus
  **/
  @Schema(required = true, description = "")
  public AgreementComplianceStatus getComplianceStatus() {
    return complianceStatus;
  }

  public void setComplianceStatus(AgreementComplianceStatus complianceStatus) {
    this.complianceStatus = complianceStatus;
  }

  public Agreement intermediarySplits(List<IntermediarySplit> intermediarySplits) {
    this.intermediarySplits = intermediarySplits;
    return this;
  }

  public Agreement addIntermediarySplitsItem(IntermediarySplit intermediarySplitsItem) {
    this.intermediarySplits.add(intermediarySplitsItem);
    return this;
  }

   /**
   * Get intermediarySplits
   * @return intermediarySplits
  **/
  @Schema(required = true, description = "")
  public List<IntermediarySplit> getIntermediarySplits() {
    return intermediarySplits;
  }

  public void setIntermediarySplits(List<IntermediarySplit> intermediarySplits) {
    this.intermediarySplits = intermediarySplits;
  }

  public Agreement effectiveDate(LocalDate effectiveDate) {
    this.effectiveDate = effectiveDate;
    return this;
  }

   /**
   * date on which this product configuration became effective
   * @return effectiveDate
  **/
  @Schema(required = true, description = "date on which this product configuration became effective")
  public LocalDate getEffectiveDate() {
    return effectiveDate;
  }

  public void setEffectiveDate(LocalDate effectiveDate) {
    this.effectiveDate = effectiveDate;
  }

  public Agreement referenceNumber(String referenceNumber) {
    this.referenceNumber = referenceNumber;
    return this;
  }

   /**
   * additional reference number for the agreement
   * @return referenceNumber
  **/
  @Schema(description = "additional reference number for the agreement")
  public String getReferenceNumber() {
    return referenceNumber;
  }

  public void setReferenceNumber(String referenceNumber) {
    this.referenceNumber = referenceNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Agreement agreement = (Agreement) o;
    return Objects.equals(this.complianceStatus, agreement.complianceStatus) &&
        Objects.equals(this.intermediarySplits, agreement.intermediarySplits) &&
        Objects.equals(this.effectiveDate, agreement.effectiveDate) &&
        Objects.equals(this.referenceNumber, agreement.referenceNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(complianceStatus, intermediarySplits, effectiveDate, referenceNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Agreement {\n");
    
    sb.append("    complianceStatus: ").append(toIndentedString(complianceStatus)).append("\n");
    sb.append("    intermediarySplits: ").append(toIndentedString(intermediarySplits)).append("\n");
    sb.append("    effectiveDate: ").append(toIndentedString(effectiveDate)).append("\n");
    sb.append("    referenceNumber: ").append(toIndentedString(referenceNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
